BridgeLib::File
uint8_t BridgeLib::File::buffered
uint8_t BridgeLib::File::readPos
uint16_t BridgeLib::File::dirPosition
uint8_t BridgeLib::File::buffer[BUFFER_SIZE]
BridgeClass & BridgeLib::File::bridge
String BridgeLib::File::filename
uint8_t BridgeLib::File::mode
uint8_t BridgeLib::File::handle
static const int BridgeLib::File::BUFFER_SIZE
BridgeLib::File::File(BridgeClass &b=Bridge)
BridgeLib::File::File(const char *_filename, uint8_t _mode, BridgeClass &b=Bridge)
BridgeLib::File::~File()
size_t BridgeLib::File::write(uint8_t)
size_t BridgeLib::File::write(const uint8_t *buf, size_t size)
int BridgeLib::File::read()
Referenced by requests.packages.urllib3.response.HTTPResponse.get_redirect_location.
int BridgeLib::File::peek()
int BridgeLib::File::available()
void BridgeLib::File::flush()
int BridgeLib::File::read(void *buf, uint16_t nbyte)
Referenced by requests.packages.urllib3.response.HTTPResponse.get_redirect_location.
boolean BridgeLib::File::seek(uint32_t pos)
uint32_t BridgeLib::File::position()
uint32_t BridgeLib::File::size()
void BridgeLib::File::close()
BridgeLib::File::operator bool()
const char * BridgeLib::File::name()
boolean BridgeLib::File::isDirectory()
File BridgeLib::File::openNextFile(uint8_t mode=FILE_READ)
void BridgeLib::File::rewindDirectory(void)
BridgeLib::File::File(BridgeClass &b=Bridge)
BridgeLib::File::File(const char *_filename, uint8_t _mode, BridgeClass &b=Bridge)
BridgeLib::File::~File()
virtual size_t BridgeLib::File::write(uint8_t)
virtual size_t BridgeLib::File::write(const uint8_t *buf, size_t size)
virtual int BridgeLib::File::read()
Referenced by requests.packages.urllib3.response.HTTPResponse.get_redirect_location.
virtual int BridgeLib::File::peek()
virtual int BridgeLib::File::available()
virtual void BridgeLib::File::flush()
int BridgeLib::File::read(void *buf, uint16_t nbyte)
Referenced by requests.packages.urllib3.response.HTTPResponse.get_redirect_location.
boolean BridgeLib::File::seek(uint32_t pos)
uint32_t BridgeLib::File::position()
uint32_t BridgeLib::File::size()
void BridgeLib::File::close()
BridgeLib::File::operator bool()
const char* BridgeLib::File::name()
boolean BridgeLib::File::isDirectory()
File BridgeLib::File::openNextFile(uint8_t mode=FILE_READ)
void BridgeLib::File::rewindDirectory(void)
void BridgeLib::File::doBuffer()
void BridgeLib::File::doBuffer()