BridgeClient
BridgeClass & BridgeClient::bridge
uint8_t BridgeClient::handle
boolean BridgeClient::opened
uint8_t BridgeClient::buffered
uint8_t BridgeClient::readPos
uint8_t BridgeClient::buffer[BUFFER_SIZE]
static const int BridgeClient::BUFFER_SIZE
BridgeClient::BridgeClient(uint8_t _h, BridgeClass &_b=Bridge)
BridgeClient::BridgeClient(BridgeClass &_b=Bridge)
BridgeClient::~BridgeClient()
int BridgeClient::available()
int BridgeClient::read()
Referenced by requests.packages.urllib3.response.HTTPResponse.get_redirect_location.
int BridgeClient::read(uint8_t *buf, size_t size)
Referenced by requests.packages.urllib3.response.HTTPResponse.get_redirect_location.
int BridgeClient::peek()
size_t BridgeClient::write(uint8_t)
size_t BridgeClient::write(const uint8_t *buf, size_t size)
void BridgeClient::flush()
virtual BridgeClient::operator bool()
BridgeClient & BridgeClient::operator=(const BridgeClient &_x)
void BridgeClient::stop()
uint8_t BridgeClient::connected()
int BridgeClient::connect(IPAddress ip, uint16_t port)
int BridgeClient::connect(const char *host, uint16_t port)
int BridgeClient::connectSSL(const char *host, uint16_t port)
BridgeClient::BridgeClient(uint8_t _h, BridgeClass &_b=Bridge)
BridgeClient::BridgeClient(BridgeClass &_b=Bridge)
BridgeClient::~BridgeClient()
virtual int BridgeClient::available()
virtual int BridgeClient::read()
Referenced by requests.packages.urllib3.response.HTTPResponse.get_redirect_location.
virtual int BridgeClient::read(uint8_t *buf, size_t size)
Referenced by requests.packages.urllib3.response.HTTPResponse.get_redirect_location.
virtual int BridgeClient::peek()
virtual size_t BridgeClient::write(uint8_t)
virtual size_t BridgeClient::write(const uint8_t *buf, size_t size)
virtual void BridgeClient::flush()
virtual BridgeClient::operator bool()
virtual BridgeClient& BridgeClient::operator=(const BridgeClient &_x)
virtual void BridgeClient::stop()
virtual uint8_t BridgeClient::connected()
virtual int BridgeClient::connect(IPAddress ip, uint16_t port)
virtual int BridgeClient::connect(const char *host, uint16_t port)
int BridgeClient::connectSSL(const char *host, uint16_t port)
void BridgeClient::doBuffer()
void BridgeClient::doBuffer()