BridgeUDP
BridgeClass & BridgeUDP::bridge
uint8_t BridgeUDP::handle
boolean BridgeUDP::opened
uint16_t BridgeUDP::avail
uint8_t BridgeUDP::buffered
uint8_t BridgeUDP::readPos
uint8_t BridgeUDP::buffer[BUFFER_SIZE]
static const int BridgeUDP::BUFFER_SIZE
BridgeUDP::BridgeUDP(BridgeClass &_b=Bridge)
uint8_t BridgeUDP::begin(uint16_t)
void BridgeUDP::stop()
int BridgeUDP::beginPacket(IPAddress ip, uint16_t port)
int BridgeUDP::beginPacket(const char *host, uint16_t port)
int BridgeUDP::beginBroadcastPacket(uint16_t port)
int BridgeUDP::endPacket()
virtual size_t BridgeUDP::write(uint8_t d)
size_t BridgeUDP::write(const uint8_t *buffer, size_t size)
int BridgeUDP::parsePacket()
virtual int BridgeUDP::available()
int BridgeUDP::read()
Referenced by requests.packages.urllib3.response.HTTPResponse.get_redirect_location.
int BridgeUDP::read(unsigned char *buffer, size_t len)
Referenced by requests.packages.urllib3.response.HTTPResponse.get_redirect_location.
virtual int BridgeUDP::read(char *buffer, size_t len)
Referenced by requests.packages.urllib3.response.HTTPResponse.get_redirect_location.
int BridgeUDP::peek()
virtual void BridgeUDP::flush()
IPAddress BridgeUDP::remoteIP()
uint16_t BridgeUDP::remotePort()
BridgeUDP::BridgeUDP(BridgeClass &_b=Bridge)
virtual uint8_t BridgeUDP::begin(uint16_t)
virtual void BridgeUDP::stop()
virtual int BridgeUDP::beginPacket(IPAddress ip, uint16_t port)
virtual int BridgeUDP::beginPacket(const char *host, uint16_t port)
virtual int BridgeUDP::beginBroadcastPacket(uint16_t port)
virtual int BridgeUDP::endPacket()
virtual size_t BridgeUDP::write(uint8_t d)
virtual size_t BridgeUDP::write(const uint8_t *buffer, size_t size)
virtual int BridgeUDP::parsePacket()
virtual int BridgeUDP::available()
virtual int BridgeUDP::read()
Referenced by requests.packages.urllib3.response.HTTPResponse.get_redirect_location.
virtual int BridgeUDP::read(unsigned char *buffer, size_t len)
Referenced by requests.packages.urllib3.response.HTTPResponse.get_redirect_location.
virtual int BridgeUDP::read(char *buffer, size_t len)
Referenced by requests.packages.urllib3.response.HTTPResponse.get_redirect_location.
virtual int BridgeUDP::peek()
virtual void BridgeUDP::flush()
virtual IPAddress BridgeUDP::remoteIP()
virtual uint16_t BridgeUDP::remotePort()
void BridgeUDP::doBuffer()
void BridgeUDP::doBuffer()